server:
  port: 1001

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示将自己注册进eurekaServer
    register-with-eureka: true
    #从eurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
  instance:
    instance-id: consumer1001
    prefer-ip-address: true