server:
  port: 1001

eureka:
  instance:
    #在eureka服务端中显示的名字
    instance-id: hystrix1001
    #在eureka服务端中，鼠标放在实例名称上，会显示ip
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间割
    lease-renewal-interval-in-seconds: 2
    #eureka服务端收到最后一次心跳后等待的时间上限，超时将剔除服务
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka

ribbon:
  #与服务端建立连接的超时时间，与网络有关
  ConnectTimeout: 1000
  #建立连接后，从服务端获取数据的超时时间
  ReadTimeout: 2000

feign:
  hystrix:
    enabled: true