server:
  port: 7001

eureka:
  instance:
    #eureka服务端实例名称
    hostname: eureka7001.com
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eurekaServer交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
  server:
    #关闭自我保护
    enable-self-preservation: false
    #客户端超时未发送心跳，剔除服务
    eviction-interval-timer-in-ms: 10000